name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm i
      - run: npm run build --if-present

      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          buildArgs: |
            PUBLIC_HELLO=world

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://larr.cc
          app: 'sveltekit'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/eumarcelo/sveltekit:latest'
